### ISSUE TITLE
DevHub

### ISSUE THREAD

**Issue by brunolemos** [nat/ghtop#9]
Hi, this reminds me of DevHub, check it out: https://github.com/devhubapp/devhub
But I didn't add a way to see ALL events, you need to at least specify something, e.g. the org.

Closing the issue as I just wanted to mention that :) 
Thanks.

<img width="1035" alt="image" src="https://user-images.githubusercontent.com/619186/101235213-521bf600-36a5-11eb-8c54-d1cbbf283a6b.png">

**Comment by nat** [comment]
DevHub is great!
